export default {
  "login": "amirhosseinNouri",
  "id": 63261053,
  "node_id": "MDQ6VXNlcjYzMjYxMDUz",
  "avatar_url": "https://avatars.githubusercontent.com/u/63261053?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/amirhosseinNouri",
  "html_url": "https://github.com/amirhosseinNouri",
  "followers_url": "https://api.github.com/users/amirhosseinNouri/followers",
  "following_url": "https://api.github.com/users/amirhosseinNouri/following{/other_user}",
  "gists_url": "https://api.github.com/users/amirhosseinNouri/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/amirhosseinNouri/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/amirhosseinNouri/subscriptions",
  "organizations_url": "https://api.github.com/users/amirhosseinNouri/orgs",
  "repos_url": "https://api.github.com/users/amirhosseinNouri/repos",
  "events_url": "https://api.github.com/users/amirhosseinNouri/events{/privacy}",
  "received_events_url": "https://api.github.com/users/amirhosseinNouri/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Amirhossein Nouri",
  "company": null,
  "blog": "https://www.linkedin.com/in/amirhossein-nouri-5a0231204/",
  "location": "Tehran",
  "email": null,
  "hireable": null,
  "bio": "Computer Engineering Student at Shahid Beheshti University",
  "twitter_username": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 4,
  "following": 5,
  "created_at": "2020-04-06T19:38:02Z",
  "updated_at": "2021-01-21T12:50:26Z"
};
