export default {
  login: "rsharifnasab",
  id: 11211946,
  node_id: "MDQ6VXNlcjExMjExOTQ2",
  avatar_url: "https://avatars.githubusercontent.com/u/11211946?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/rsharifnasab",
  html_url: "https://github.com/rsharifnasab",
  followers_url: "https://api.github.com/users/rsharifnasab/followers",
  following_url:
    "https://api.github.com/users/rsharifnasab/following{/other_user}",
  gists_url: "https://api.github.com/users/rsharifnasab/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/rsharifnasab/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/rsharifnasab/subscriptions",
  organizations_url: "https://api.github.com/users/rsharifnasab/orgs",
  repos_url: "https://api.github.com/users/rsharifnasab/repos",
  events_url: "https://api.github.com/users/rsharifnasab/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/rsharifnasab/received_events",
  type: "User",
  site_admin: false,
  name: "Roozbeh Sharifnasab",
  company: "Shahid Beheshti University",
  blog: "rsharifnasab.ir",
  location: "Iran, Tehran",
  email: null,
  hireable: null,
  bio: "\r\n    someone who wants to learn\r\n",
  twitter_username: null,
  public_repos: 60,
  public_gists: 1,
  followers: 163,
  following: 209,
  created_at: "2015-02-26T12:56:47Z",
  updated_at: "2021-01-18T05:20:12Z",
};
